#!/usr/bin/env bash
# Confluence - mainnet bridge offers only chains with Circle Forwarding as destination.
# Changes: confluence-api/src/chains/registry.ts (testnet unchanged).
# Usage: bash stage-mainnet-forwarding-only.sh [--dry-run | --revert]
set -euo pipefail

REPO="${CONFLUENCE_REPO:-$HOME/confluence}"
FILE="confluence-api/src/chains/registry.ts"
MARKER="confluence:mainnet-forwarding-only"
OLD_SHA="a23b345b96f725291260f4f55990f7992b36af57a2b7d695d85f076810099b21"
NEW_SHA="6932d75121429a7426695390b44b35702b567c1af3e2ed1c61fc189381b125f2"
BACKUP_DIR="$REPO/.confluence/backups"
MODE="${1:-apply}"

cd "$REPO" || { echo "repo not found at $REPO"; exit 1; }
[ -f "$FILE" ] || { echo "missing $FILE"; exit 1; }
sha() { sha256sum "$1" | cut -d' ' -f1; }

if [ "$MODE" = "--revert" ]; then
  LAST=$(ls -1t "$BACKUP_DIR"/registry.ts.*.bak 2>/dev/null | head -1 || true)
  [ -n "$LAST" ] || { echo "no backup found in $BACKUP_DIR"; exit 1; }
  [ "$(sha "$LAST")" = "$OLD_SHA" ] || { echo "backup $LAST is not the expected original; not reverting"; exit 1; }
  cp "$LAST" "$FILE"
  echo "reverted $FILE from $LAST"
  exit 0
fi

CUR=$(sha "$FILE")
if [ "$CUR" = "$NEW_SHA" ] || grep -q "$MARKER" "$FILE"; then
  echo "already applied (marker present); nothing to do"; exit 0
fi
[ "$CUR" = "$OLD_SHA" ] || { echo "$FILE is not in the expected prior state (sha $CUR); not touching it"; exit 1; }

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
base64 -d > "$TMP" <<'B64'
aW1wb3J0IHsgQXBwS2l0IH0gZnJvbSAiQGNpcmNsZS1maW4vYXBwLWtpdCI7CmltcG9ydCB0eXBlIHsgQ29uZmlnIH0gZnJvbSAiLi4vY29uZmlnLmpzIjsKaW1wb3J0IHsgZmluYWxpdHlGb3IsIHR5cGUgRmluYWxpdHlJbmZvIH0gZnJvbSAiLi9maW5hbGl0eS5qcyI7CgpleHBvcnQgY29uc3QgRklOQUxJVFlfU09VUkNFX1VSTCA9ICJodHRwczovL2RldmVsb3BlcnMuY2lyY2xlLmNvbS9jY3RwL2NvbmNlcHRzL2ZpbmFsaXR5LWFuZC1ibG9jay1jb25maXJtYXRpb25zIjsKCmV4cG9ydCBpbnRlcmZhY2UgQnJpZGdlQ2hhaW4gewogIC8qKiBBcHAgS2l0IGNoYWluIGlkZW50aWZpZXIsIGUuZy4gIkFyY19UZXN0bmV0Ii4gQ2FzZS1zZW5zaXRpdmUuICovCiAgaWQ6IHN0cmluZzsKICBuYW1lOiBzdHJpbmc7CiAgZXZtQ2hhaW5JZDogbnVtYmVyOwogIGNjdHBEb21haW46IG51bWJlcjsKICBpc1Rlc3RuZXQ6IGJvb2xlYW47CiAgLyoqIEV4cGxvcmVyIFVSTCB0ZW1wbGF0ZSBjb250YWluaW5nICJ7aGFzaH0iICovCiAgZXhwbG9yZXJUeFVybDogc3RyaW5nOwogIHVzZGNBZGRyZXNzOiBzdHJpbmc7CiAgLyoqIE5hdGl2ZSBnYXMgdG9rZW4sIGFzIHJlcG9ydGVkIGJ5IEFwcCBLaXQgKG9uIEFyYyB0aGlzIGlzIFVTREMpLiAqLwogIG5hdGl2ZUN1cnJlbmN5OiB7IG5hbWU6IHN0cmluZzsgc3ltYm9sOiBzdHJpbmc7IGRlY2ltYWxzOiBudW1iZXIgfTsKICAvKiogUHVibGljIFJQQyBlbmRwb2ludHMgZnJvbSBBcHAgS2l0OyB0aGUgZmlyc3QgaXMgcHJpbWFyeS4gKi8KICBycGNVcmxzOiBzdHJpbmdbXTsKICAvKiogV2hldGhlciBDaXJjbGUncyBGb3J3YXJkaW5nIFNlcnZpY2UgY2FuIG1pbnQgb24gdGhpcyBjaGFpbiBhcyB0aGUgZGVzdGluYXRpb24uICovCiAgZm9yd2FyZGVyQXNEZXN0aW5hdGlvbjogYm9vbGVhbjsKICAvKiogQ0NUUCB2MiBNZXNzYWdlVHJhbnNtaXR0ZXIgKGRlc3RpbmF0aW9uIG1pbnRzKSwgZnJvbSBBcHAgS2l0OyBudWxsIGlmIG5vdCBsaXN0ZWQuICovCiAgbWVzc2FnZVRyYW5zbWl0dGVyOiBzdHJpbmcgfCBudWxsOwogIC8qKiBTb3VyY2Utc2lkZSBhdHRlc3RhdGlvbiB0aW1lcyBmcm9tIENpcmNsZSdzIGRvY3M7IG51bGwgd2hlbiBub3QgbGlzdGVkLiAqLwogIHNwZWVkOiBGaW5hbGl0eUluZm8gfCBudWxsOwp9CgpleHBvcnQgaW50ZXJmYWNlIENoYWluUmVnaXN0cnkgewogIHJlYWRvbmx5IGNoYWluczogcmVhZG9ubHkgQnJpZGdlQ2hhaW5bXTsKICByZWFkb25seSBieUlkOiBSZWFkb25seU1hcDxzdHJpbmcsIEJyaWRnZUNoYWluPjsKICAvKiogU3VwcG9ydGVkIGNoYWlucyB0aGF0IGhhdmUgbm8gZW50cnkgaW4gdGhlIGZpbmFsaXR5IHRhYmxlIChzaG93biB3aXRob3V0IEVUQSkuICovCiAgcmVhZG9ubHkgbWlzc2luZ1NwZWVkOiByZWFkb25seSBzdHJpbmdbXTsKfQoKLyoqIEFwcCBLaXQncyB2MiBjb250cmFjdCBibG9jayBpcyBlaXRoZXIgInNwbGl0IiAod2l0aCBtZXNzYWdlVHJhbnNtaXR0ZXIpIG9yIG1lcmdlZC4gKi8KZnVuY3Rpb24gbWVzc2FnZVRyYW5zbWl0dGVyT2YoY2N0cDogdW5rbm93bik6IHN0cmluZyB8IG51bGwgewogIGNvbnN0IHYyID0gKGNjdHAgYXMgeyBjb250cmFjdHM/OiB7IHYyPzogUmVjb3JkPHN0cmluZywgdW5rbm93bj4gfSB9IHwgdW5kZWZpbmVkKT8uY29udHJhY3RzPy52MjsKICBjb25zdCBhZGRyID0gdjI/LlsibWVzc2FnZVRyYW5zbWl0dGVyIl07CiAgcmV0dXJuIHR5cGVvZiBhZGRyID09PSAic3RyaW5nIiAmJiAvXjB4WzAtOWEtZkEtRl17NDB9JC8udGVzdChhZGRyKSA/IGFkZHIgOiBudWxsOwp9CgovKioKICogQnVpbGRzIHRoZSBicmlkZ2UgY2hhaW4gbGlzdCBmcm9tIHRoZSBpbnN0YWxsZWQgQXBwIEtpdCBTREssIG5ldmVyIGEgaGFyZC1jb2RlZCBsaXN0LgogKiB2MSBpcyBFVk0gb25seTsgdGVzdG5ldCBidWlsZHMgb25seSBzZWUgdGVzdG5ldHMgYW5kIG1haW5uZXQgb25seSBtYWlubmV0cy4KICogTWFpbm5ldCBvbmx5IG9mZmVycyBjaGFpbnMgd2hlcmUgQ2lyY2xlJ3MgRm9yd2FyZGluZyBTZXJ2aWNlIGNhbiBtaW50IG9uIHRoZQogKiBkZXN0aW5hdGlvbiAoY29uZmx1ZW5jZTptYWlubmV0LWZvcndhcmRpbmctb25seSk7IHRlc3RuZXQga2VlcHMgZXZlcnkgY2hhaW4uCiAqLwpleHBvcnQgZnVuY3Rpb24gYnVpbGRDaGFpblJlZ2lzdHJ5KGNvbmZpZzogQ29uZmlnLCBraXQ6IFBpY2s8QXBwS2l0LCAiZ2V0U3VwcG9ydGVkQ2hhaW5zIj4gPSBuZXcgQXBwS2l0KCkpOiBDaGFpblJlZ2lzdHJ5IHsKICBjb25zdCB3YW50VGVzdG5ldCA9IGNvbmZpZy5DT05GTFVFTkNFX0VOViA9PT0gInRlc3RuZXQiOwogIGNvbnN0IGNoYWluczogQnJpZGdlQ2hhaW5bXSA9IFtdOwogIGZvciAoY29uc3QgYyBvZiBraXQuZ2V0U3VwcG9ydGVkQ2hhaW5zKCJicmlkZ2UiKSkgewogICAgaWYgKGMudHlwZSAhPT0gImV2bSIgfHwgYy5pc1Rlc3RuZXQgIT09IHdhbnRUZXN0bmV0IHx8ICFjLnVzZGNBZGRyZXNzIHx8ICFjLmNjdHApIGNvbnRpbnVlOwogICAgaWYgKCF3YW50VGVzdG5ldCAmJiAhYy5jY3RwLmZvcndhcmRlclN1cHBvcnRlZD8uZGVzdGluYXRpb24pIGNvbnRpbnVlOwogICAgY2hhaW5zLnB1c2goewogICAgICBpZDogYy5jaGFpbiwKICAgICAgbmFtZTogYy5uYW1lLAogICAgICBldm1DaGFpbklkOiBjLmNoYWluSWQsCiAgICAgIGNjdHBEb21haW46IGMuY2N0cC5kb21haW4sCiAgICAgIGlzVGVzdG5ldDogYy5pc1Rlc3RuZXQsCiAgICAgIGV4cGxvcmVyVHhVcmw6IGMuZXhwbG9yZXJVcmwsCiAgICAgIHVzZGNBZGRyZXNzOiBjLnVzZGNBZGRyZXNzLAogICAgICBuYXRpdmVDdXJyZW5jeTogeyBuYW1lOiBjLm5hdGl2ZUN1cnJlbmN5Lm5hbWUsIHN5bWJvbDogYy5uYXRpdmVDdXJyZW5jeS5zeW1ib2wsIGRlY2ltYWxzOiBjLm5hdGl2ZUN1cnJlbmN5LmRlY2ltYWxzIH0sCiAgICAgIHJwY1VybHM6IFsuLi5jLnJwY0VuZHBvaW50c10sCiAgICAgIGZvcndhcmRlckFzRGVzdGluYXRpb246IGMuY2N0cC5mb3J3YXJkZXJTdXBwb3J0ZWQuZGVzdGluYXRpb24sCiAgICAgIG1lc3NhZ2VUcmFuc21pdHRlcjogbWVzc2FnZVRyYW5zbWl0dGVyT2YoYy5jY3RwKSwKICAgICAgc3BlZWQ6IGZpbmFsaXR5Rm9yKGMuY2hhaW4pLAogICAgfSk7CiAgfQogIC8vIEFyYyBmaXJzdCAodGhlIHByb2R1Y3QgY2VudGVycyBvbiBpdCksIHRoZW4gYWxwaGFiZXRpY2FsIGJ5IG5hbWUuCiAgY2hhaW5zLnNvcnQoKGEsIGIpID0+IHsKICAgIGNvbnN0IGFyY0EgPSBhLmlkLnN0YXJ0c1dpdGgoIkFyYyIpID8gMCA6IDE7CiAgICBjb25zdCBhcmNCID0gYi5pZC5zdGFydHNXaXRoKCJBcmMiKSA/IDAgOiAxOwogICAgcmV0dXJuIGFyY0EgLSBhcmNCIHx8IGEubmFtZS5sb2NhbGVDb21wYXJlKGIubmFtZSk7CiAgfSk7CiAgcmV0dXJuIE9iamVjdC5mcmVlemUoewogICAgY2hhaW5zOiBPYmplY3QuZnJlZXplKGNoYWlucyksCiAgICBieUlkOiBuZXcgTWFwKGNoYWlucy5tYXAoKGMpID0+IFtjLmlkLCBjXSkpLAogICAgbWlzc2luZ1NwZWVkOiBPYmplY3QuZnJlZXplKGNoYWlucy5maWx0ZXIoKGMpID0+ICFjLnNwZWVkKS5tYXAoKGMpID0+IGMuaWQpKSwKICB9KTsKfQo=
B64
[ "$(sha "$TMP")" = "$NEW_SHA" ] || { echo "decoded file failed sha256 check; aborting"; exit 1; }

if [ "$MODE" = "--dry-run" ]; then
  echo "dry run: prior state OK, payload OK. Changes that would be applied:"
  diff -u "$FILE" "$TMP" || true
  exit 0
fi

mkdir -p "$BACKUP_DIR"
STAMP=$(date +%Y%m%d-%H%M%S)
cp "$FILE" "$BACKUP_DIR/registry.ts.$STAMP.bak"
cp "$TMP" "$FILE"
echo "applied. backup: $BACKUP_DIR/registry.ts.$STAMP.bak"
echo "next: cd confluence-api && npm run typecheck"
